### PR TITLE
Added support for unparsed SubPackets

### PR DESCRIPTION
**Pull request by nielslaukens**
This way a PacketFactory->parse() followed by a save() does not loose
data.

### CODE REVIEW

**Comment by sergeyromanov** [comment]
Thanks a lot for your PRs!

It'd be really nice if could you add unit tests for this patch (and other as well, where possible). That way it would be much easier to verify you contributions.

Cheers!

**Comment by nielslaukens** [comment]
How should I run these tests? The usual `make test` is missing a Makefile...

**Comment by sergeyromanov** [comment]
Since the dist is managed by `Dist::Zilla` your best option for now is to install that first:

    cpanm Dist::Zilla
    dzil authordeps |cpanm

After that you should be able to build the dist

    dzil build
 and run the whole testsuite

    dzil test
or individual test file

    dzil run prove -wl t/01-util.t
I know that this is quite far from convenient contribution workflow. Hopefully I'll have time to look into ways of improving this.

Thanks again!

**Comment by nielslaukens** [comment]
I can't get Dist::Zilla to work on my system...
But I've run the tests manually, and they seem to have the proper behavior (i.e. fail once I introduce a new test, pass once I introduce the fix). I've added test-suites to all pull-requests.

**Comment by timlegge** [comment]
Merged and trial release at https://metacpan.org/release/TIMLEGGE/Crypt-OpenPGP-1.14-TRIAL

**Comment by timlegge** [comment]
@nielslaukens this issue can be closed too

**Pull request closed without merging**
