### PR TITLE
Added UserAttribute class (unparsed)

### PR DESCRIPTION
**Pull request by nielslaukens**

### CODE REVIEW

**Comment by sergeyromanov** [comment]
I should've looked at those long ago, sorry about that!

First of all, thanks for your work! It seem like something's wrong with you pull requests, however. Some commits (e.g. 055a884) appear in multiple PRs at the same time. Is it possible for you to resubmit (we can discuss, of course).

**Comment by nielslaukens** [comment]
Yes, 055a884 indeed appears in multiple pull requests, because it's common: I first added a test harness to run packets through a parse/save cycle, and compare the result to the original (055a884).
Then, I worked on the different problem cases by adding a test packet, and fixing the code. All different test-packets make use of the same common test harness.

What might be easier to pull in, is that I combine the different patches into one pull request?

**Comment by timlegge** [comment]
Merged and trial release at https://metacpan.org/release/TIMLEGGE/Crypt-OpenPGP-1.14-TRIAL

**Comment by timlegge** [comment]
@nielslaukens Can be closed - Released in 1.15 to CPAN

**Comment by nielslaukens** [comment]
Do you want me to close these?

**Comment by timlegge** [comment]
Please

**Comment by timlegge** [comment]
I don't have admin on this repo so I cannot close

**Pull request closed without merging**
